### PR TITLE
feat: animate: allow following while stopping at inputs EOF

### PR DESCRIPTION
**Pull request by AdrianDC**
* Test:
    - seq 1 100 | shuf >./tests/tmp.1.raw
    - seq 1 150 | shuf >./tests/tmp.2.raw
    - seq 1 200 | shuf >./tests/tmp.3.raw
    - ./build/plot -c C -A -i ./tests/tmp.1.raw -c R \
        -i ./tests/tmp.2.raw -c G -i ./tests/tmp.3.raw \
        -S 200 -x 5: -y 10:3:1
    - rm -f ./tests/tmp.1.raw ./tests/tmp.2.raw ./tests/tmp.3.raw

### CODE REVIEW

**Comment by AdrianDC** [comment]
WIP: This handles "animated" --follow for finite data inputs or streams, however it breaks real --follow of unfinished streams.
I'd consider an additional flag or --animate alternative to --follow that would handle EOF this way.

**Comment by AdrianDC** [comment]
Handled separately as "-A" for animate, with related documentation;

Pushed on top of the -b bound feature to avoid conflict resolution for the moment.

**Comment by annacrombie** [comment]
I'm a little hesitant to add this, since `-f` already feels a bit hacky, but I'm not totally against it.

**Comment by annacrombie** [comment]
I will review this after we figure out #11

**Comment by AdrianDC** [comment]
Follows #11

I fixed an issue in the `getopt` syntax, a follow-up commit fixes the additional \n output that the normal output with the same input data does not add, and a minor error messages fixes commit.

**Comment by annacrombie** [comment]
I will go ahead and merge this for now.  I think a rewrite of input.c is in order, which will also let us clean up this feature.  Until then this is good!

**Pull request merged**
