### PR TITLE
feat: bump version to 0.4.0, test: minor codestyle improvements and 'plot' binary fallbacks 

### PR DESCRIPTION
**Pull request by AdrianDC**

### CODE REVIEW

**Comment by AdrianDC** [comment]
`set -eux` : Support sh ./tests/basic.sh rather than hashbang calls only

`plot="${1:-plot}"` : Default fallback to installed plot binary

`rm -f tmp1 tmp2 tmp3` : Cleanup temporary files after tests

**Comment by annacrombie** [comment]
I commented on the version bump in the other PR, oops!

> set -eux : Support sh ./tests/basic.sh rather than hashbang calls only

fair

> plot="${1:-plot}" : Default fallback to installed plot binary

This is okay I guess, but then you might accidentally run tests against an old version of plot.  I could see myself getting confused.

> rm -f tmp1 tmp2 tmp3 : Cleanup temporary files after tests

I removed this because it doesn't really affect the tests.  Also, it isn't robust at all, if a test fails the files will remain.  Finally, the temporary files should all be in the temporary meson directory anyway, so you shouldn't see them.

I encourage you to run the tests via `meson test -C build/` which will ensure `plot` is up to date, ensure tests are reproducable, etc.

Check `meson test -h` for more info, for example `meson test -C build -v --num-processes 1` will be basically the same as running the test directly.

**Comment by AdrianDC** [comment]
Thanks for the comments.

I added a 'Testing' section to reference the test commands, removed the parameter fallback and the files cleanups.

**Comment by annacrombie** [comment]
LGTM

**Pull request merged**
