### PR TITLE
docs: fix the network monitor example

### PR DESCRIPTION
**Pull request by AdrianDC**
@holmanb

### CODE REVIEW

**Comment by holmanb** [comment]
:+1:

**Comment by annacrombie** [comment]
Any preference over this vs #4?

**Comment by holmanb** [comment]
@annacrombie No preference from me, I'll close #4.

**Comment by annacrombie** [comment]
@AdrianDC @holmanb after testing this, I found that it is broken on my system.  It seems the output of ifconfig is not standard.  I had the idea to simply read `/sys/class/net/<interface>/statistics/{rx,tx}_packets`.  When that worked well, I realized there are actually a lot of files just like this in `/sys` so I simplified the example to allow "monitoring" based on arbitrary files.  You can find the new script at `examples/monitor`.

I also updated the docs build system to include the text of the example script in the docs for easy testing of the example.

If the new script is satisfactory, I will close this pr.  Thanks again for reporting this!

**Comment by holmanb** [comment]
No complaints from on this approach.  A kernel interface will likely be more than a userspace utility in general, so this seems like a better path.  That said, your example appears to depend on a function that isn't implemented (`die`).

**Comment by annacrombie** [comment]
> your example appears to depend on a function that isn't implemented (`die`).
Nice catch!  I was trying to make it as simple as possible, but I accidentally removed too much.  I just pushed a fix

**Comment by annacrombie** [comment]
If everything looks good, I will give @AdrianDC some time to respond, then I'll close this

**Comment by holmanb** [comment]
I see your fix and it looks good to me.

**Comment by AdrianDC** [comment]
Fine by me

**Pull request closed without merging**
