### PR TITLE
feat: implement CentOS 6/7 RPM builds and release version 0.4.0-1

### PR DESCRIPTION
**Pull request by AdrianDC**

### CODE REVIEW

**Comment by AdrianDC** [comment]
Depends on #14 

Meant for CentOS developers / users obviously.

Reference builds running with GitLab CI (which I'll use internally),
it can be launched locally with https://pypi.org/project/gitlabci-local

**Comment by annacrombie** [comment]
First of all, thanks for all of your contributions to plot!

I'm fine with a version bump, but I'd rather make that commit along with a tag outside of a PR.

As far as the RPM goes, the way it is done in this PR seems a little ugly to me (a giant `SPECS` folder and several others by the looks of the .gitignore in the project root), not to mention setting a bad example for future integration with other package managers.  I am unfamiliar with rpm packaging, so maybe design this was unavoidable.  If you can refactor so that all of the files are contained under something like `pkg/rpm` then I will consider merging this.  Bonus points if you integrate it with meson, though I can probably figure that out later.

If you don't want to do this, then I encourage you to put these rpm build scripts in a separate repo, and I would be happy to link to it in the readme/wiki!

**Comment by AdrianDC** [comment]
I rebased on the first PR and isolated the spec to "packaging" and intermediates to "build/redhat",
avoids spamming the plot project with changes, unlike our usual RPM build projets.

**Comment by annacrombie** [comment]
> avoids spamming the plot project with changes, unlike our usual RPM build projets.

ty :smile:

**Comment by annacrombie** [comment]
LGTM

**Pull request merged**
